development:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: bingo_bango_development
  pool: 500
  username: postgres
  password:
  min_messages: warning

production:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: bingo_bango_production
  pool: 500
  username: postgres
  password:
  min_messages: warning
